### ISSUE TITLE
use table variable rather than #temp table, and use subquery

### ISSUE THREAD

**Issue by DickBaker** [yorek/practical-azure-sql-db-for-modern-developers#11]
p114 sproc creates and populates a temporary table but fails to drop it afterwards, so re-executing sproc from same SPID would fail
 should create+use a table variable instead

in any case that SELECT should ideally include the DISTINCT keyword

but much better if the main SELECT statement used a subquery instead, e.g.
  CustomerID in (SELECT DISTINCT OPENJSON(@CustomerInfo, '$.CustomerID))

**Comment by yorek** [comment]
Not sure if you have tried to execute the code. It will work perfectly. Once a created local temporary table goes out of scope, it will be automatically dropped. 

DISTINCT is very resource intensive, there is no need to use it unless you know that there can be duplicates and you want to get rid of them.

**Comment by DickBaker** [comment]
agree DISTINCT would involve a sort (often an index is available to avoid such extra work). Book's code will work but will have more compares is there are actially dupes.

Rather than having several statements and creating a temporary table, it is always better perf to combine into a single (more complex) statement and let the optimiser decide the best strategy. The example is also easy-enough for human readability (I would agree that a 1-line monster statement could be difficult to comprehend!).
