### ISSUE TITLE
peddling outdated guidance

### ISSUE THREAD

**Issue by DickBaker** [yorek/practical-azure-sql-db-for-modern-developers#4]
.NET Core 3.0 shipped 23/9/2019 and introduced the latest IAsyncEnumerable interface for improved streaming performance. Unfortunately the APress book publishes outdated ADO sample (e.g. Listing 3-1 et al) having pulled the entire resultset (this can have severe issues with performance and memory contention as well described by Anthony Chu at https://anthonychu.ca/post/async-streams-dotnet-core-3-iasyncenumerable/). I am about to raise a PR to show modern guidance.

**Comment by yorek** [comment]
Thanks, will take a look ASAP!
