### ISSUE TITLE
explicit ORDERBY please

### ISSUE THREAD

**Issue by DickBaker** [yorek/practical-azure-sql-db-for-modern-developers#7]
on pp73-75 book shows simple SELECT with an ORDER BY clause
- but the "more complex sample" on p74 (and pp78-79) then forgets this basic advice (doh!)

TSQL code also does an unnecessary CAST to DATE because the ConfirmedDeliveryTime is already of datatype Datetime2(7)

Because this field is computed (but not persisted) via (both queries)
  TRY_CONVERT([datetime2](7),json_value([ReturnedDeliveryData],N'$.DeliveredWhen'),(126))
it is Non-Sargable and inefficient, but that is consequence of WideWorldImporters design and not your usage thereof

P.S. thanks for previously accepting my Issue #4, PR #5 !

**Comment by yorek** [comment]
Not sure what is the issue here. `ORDER BY` is used in the first sample to introduce the concept that there is no inherent ordering. In the more complex sample it is not used as not needed, as the concept was already clarified.

`CAST` is needed to make sure that the time part of a DateTime is not used, so that you can only focus on the dates.

**Comment by DickBaker** [comment]
Readers might reasonably expect examples building up to the "complex example" should embody the lessons from earlier simpler examples, hence my advice to include the ORDER BY both here and generally for reader consideration. IMHO it is better to avoid surprises that might arise by leaving such matters indeterminate.

CAST is **not** needed for the TSQL example shown because the **ConfirmedDeliveryTime** computed field is of type Datetime2(7) so the code will compile the literals to that date+time format prior to executing the predicate. Thus my point that you should let the TSQL compiler to its thing and not uglify the example code with an unnecessary CAST.

Elsewhere guidance is to avoid UDFs as they can introduce performance problems, and any similar function/CAST/CONVERT can equally cause grief. If you don't need it, don't use it (YAGNI)!

**Comment by yorek** [comment]
@DickBaker `CAST` **is needed** as the `ConfirmedDeliveryTime` contains not only date, but also time. Since the predicate is using a BETWEEN operator, without the cast to the `date` type, the predicate would be read as:

`i.ConfirmedDeliveryTime BETWEEN '2016-01-01 00:00:00' AND '2016-03-31 00:00:00'`

which you can see how wrong would that be. Right? :)

**Comment by yorek** [comment]
Also scalar UDFs have overhead that doesn't affect system functions like `CAST` or `CONVERT`. If we put the ability to use an index aside for a second, there is no harm in using `CAST` or `CONVERT` if needed. In this specific case, in addition, converting a `DATETIME2` to a `DATE` doesn't even incur in the problem of preventing index usage, as optimizer is smart enough to understand that if there is an index on `ConfirmedDeliveryTime` and you are casting it do a `date` type, you're basically doing a prefix-search so index *can* be used to seek data efficiently.

**Comment by DickBaker** [comment]
i.ConfirmedDeliveryTime BETWEEN '2016-01-01' AND '2016-03-31' works fine - seems compiler is smarter than you think. Right?

imho fluff is unnecessary and distracts reader, and any such frippery can often lead to nonsargable perf problems. Unfortunately importance of SARG (Search ARGument ABLE) is not adequately explained. Perhaps test,test,test explains it better (YMMV!)

**Comment by yorek** [comment]
Just run the query and see yourself. This query

```sql
select count(*) from Sales.[Invoices] i
where i.ConfirmedDeliveryTime BETWEEN '2016-01-01' AND '2016-03-31'
```

returns 5309 rows, this one

```sql
select count(*) from Sales.[Invoices] i
where cast(i.ConfirmedDeliveryTime as date) BETWEEN '2016-01-01' AND '2016-03-31'
```

returns 5397 rows. Of course the second one is the one that returns the data you would expect. In the first one, as explained before, all deliveries done in the day of 31st March 2016 will not be present. Not sure how you tested the query to conclude that "it works fine" :)
