### ISSUE TITLE
missing ORDER BY clause

### ISSUE THREAD

**Issue by DickBaker** [yorek/practical-azure-sql-db-for-modern-developers#9]
the code on pp98-99 includes the ORDER BY clause on the windowing function column but omits it on the parent SELECT

**Comment by yorek** [comment]
Again, not sure why you have the impression that if `ORDER BY` is used in the `OVER` clause it also must be used in the `SELECT` statement, but that's not the case. `ORDER BY` in the `OVER` clause is used to provide an order on which the operator of the window clause can work on, but the resulting result set can be unordered.

**Comment by DickBaker** [comment]
fair enuff, thanks
